### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dp-ifacesoft** [artemBilik/emmet#8]
'div.Admin_Access_Book_Packet[data-action="Ice\Action\View_Render" data-view="Ice\Action\View_Render" data-params="test" data-url="/ice/admin/access/book/packet"]' 
                   ^
                   ||

``` html
<div class="Admin_Access_Book_Packet" iceadminaccessbookpacket""="" data-url="" test""="" data-params="" data-view="" ice\action\view_render""="" data-action="">
```

**Comment by artemBilik** [comment]
1 - кавычки не нужны [data-action="Ice\Action\View_Render" - оставь без кавычек
2 - с экранированием я натупил экранирование теперь через \ Ice\Action\View_Render
    Нет с экранированием все не так
    экранированме через /
    соответственно /ice/admin/access/book/packet -> //ice//admin//access//book//packet
3 - html строка внизу это то что получилось? может у тебя старая версия?

**Comment by artemBilik** [comment]
Нет с экранированием все не так
экранированме через /
соответственно /ice/admin/access/book/packet   -> //ice//admin//access//book//packet

**Comment by dp-ifacesoft** [comment]
1. В доке для строк кавычки
2. Опять же я не хочу сам заведомо ничего экранировать - тусть этим еммет занимается
3. Я скачал zip архив - последняя версия из master
