### ISSUE TITLE
bug2

### ISSUE THREAD

**Issue by dp-ifacesoft** [artemBilik/emmet#9]
'div.Admin_Access_Book_Packet[data-action="Ice\Action\View_Render" data-view="Ice\Action\View_Render" data-params="[]" data-url="/ice/admin/access/book/packet"]'
                   ^
                   ||
There was an error in your Emmet string. Check the documentation for the right syntax to use near "div.Admin_Access_Book_Packet[data-action="Ice\Action\View_Render" data-view="Ice\Action\View_Render" data-params="[]" data-url="/ice/admin/access/book/packet"]{`viewContent`}". - Ebs\View\Admin_Access_Book_Packet (/ebs/vendor/ifacesoft/ice/Source/artem_c/emmet/Emmet.php:394)

**Comment by artemBilik** [comment]
я так понимаю ошибка в data-params="[]"
должно было быть выделено красным
нужно экранировать []  -> /[/]

**Comment by dp-ifacesoft** [comment]
Собственно, да.. Если я точно знаю что у меня в строке [], я заэкранирую, но если у меня эти данные получаются динамически - я хз что там будет и какие символы нужно экранировать. Хорошо бы что бы сам еммет екранировал строку в значении атрибута
